const { SlashCommandBuilder } = require('discord.js');
const { timestampstyles, timezonesgmtminus, timezonesgmtplus, timezoneskey, monthsoption, alltimezones, mathargs, dicetypes } = require('./constants.js');
const { getLoc } = require('./functions.js');
const { get } = require('lodash');

const hosa = {}; //Init commands object

//Helpers
//.setDefaultMemberPermissions(0) restricts usage to admins only. 
//.setContexts(0, 1, 2) 0 - Can be used in server channels, 1 - Can be used in DM with app's bot user, 2 - Can be used in private channels without inviting the bot
//.setIntegrationTypes(0, 1) - 0 - Can be used with bot installed on server, 1 - can be used with bot installed as User App
const setAvailable = (builder) => builder.setIntegrationTypes(0, 1).setContexts(0, 1, 2);

//decide if reply be ephemeral (publicreply: false / true)
const addPublicReply = () => (option) => {
    option.setName('publicreply')
    .setDescription('Make the result visible to everyone in the chat')
    .setDescriptionLocalizations(getLoc('publicreply'))
    .setRequired(false);
    return option;
};


//CommandBuilder
hosa.ping = new SlashCommandBuilder()
    .setName('ping')
    .setDescription('🏓 Check Application response time')
    .setDescriptionLocalizations(getLoc('checkping', '🏓 '))
    setAvailable(hosa.ping)

hosa.about = new SlashCommandBuilder()
    .setName('about')
    .setDescription('📙 About this app')
    .setDescriptionLocalizations(getLoc('aboutapp', '📙 '))
    setAvailable(hosa.about)

hosa.invite = new SlashCommandBuilder()
    .setName('invite')
    .setDescription('🔗 Install TimestampHosa app on Server or as personal app!')
    .setDescriptionLocalizations(getLoc('installapp', '🔗 '))
    setAvailable(hosa.invite)

hosa.timenow = new SlashCommandBuilder()
    .setName('now')
    .setDescription('⏱ Display current time and timestamp')
    .setDescriptionLocalizations(getLoc('descnow', '⏱ '))
    setAvailable(hosa.timenow)
    .addStringOption(option =>
        option.setName('style')
        .setNameLocalizations(getLoc('arg.style'))
        .setDescription('Select style of date output')
        .setDescriptionLocalizations(getLoc('selectstyleformat'))
        .setRequired(false)
        .addChoices(timestampstyles)
    )
    .addBooleanOption(addPublicReply())
        
hosa.timezonenow = new SlashCommandBuilder()
    .setName('timezone')
    .setDescription('🕒 Display current time in selected timezone')
    setAvailable(hosa.timezonenow)
hosa.timezonenow.addSubcommand(subcommand =>
    subcommand.setName('gmtplus')
    .setDescription('🕒 Select timezone from GMT to GMT +14')
    .setDescriptionLocalizations(getLoc('desctimezoneplus', '🕒 '))
    .addStringOption(option =>
        option.setName('timezone')
        .setNameLocalizations(getLoc('arg.timezone'))
        .setDescription('Select timezone')
        .setDescriptionLocalizations(getLoc('selecttimezone'))
        .setRequired(true)
        .addChoices(timezonesgmtplus)
    )
    .addBooleanOption(addPublicReply())
)
hosa.timezonenow.addSubcommand(subcommand =>
        subcommand.setName('gmtminus')
        .setDescription('🕒 Select timezone from GMT -12 to GMT')
        .setDescriptionLocalizations(getLoc('desctimezoneminus', '🕒 '))
        .addStringOption(option =>
            option.setName('timezone')
            .setNameLocalizations(getLoc('arg.timezone'))
            .setDescription('Select timezone')
            .setDescriptionLocalizations(getLoc('selecttimezone'))
            .setRequired(true)
            .addChoices(timezonesgmtminus)
        )
        .addBooleanOption(addPublicReply())
    )
hosa.timezonenow.addSubcommand(subcommand =>
        subcommand.setName('keyzones')
        .setDescription('🕒 Check time in timezone different from GMT')
        .setDescriptionLocalizations(getLoc('desctimezonekey', '🕒 '))
        .addStringOption(option =>
            option.setName('timezone')
            .setNameLocalizations(getLoc('arg.timezone'))
            .setDescription('Select timezone')
            .setDescriptionLocalizations(getLoc('selecttimezone'))
            .setRequired(true)
            .addChoices(timezoneskey)
        )
        .addBooleanOption(addPublicReply())
    )
        
hosa.timestampint = new SlashCommandBuilder()
    .setName('timestamp')
    .setDescription('⏳ Create timestamp to embed it in your message!')
    .setDescriptionLocalizations(getLoc('desctimestamp', '⏳ '))
    setAvailable(hosa.timestampint)
    .addIntegerOption(option =>
        option.setName('year')
        .setNameLocalizations(getLoc('arg.year'))
        .setDescription('Type Year of timestamp you want to do')
        .setDescriptionLocalizations(getLoc('typetimestampyear'))
        .setMinValue(1901)
        .setMaxValue(2999)
        .setRequired(true)
    )
    .addStringOption(option =>
        option.setName('month')
        .setNameLocalizations(getLoc('arg.month'))
        .setDescription('Select Month of timestamp you want to do')
        .setDescriptionLocalizations(getLoc('seltimestampmonth'))
        .setRequired(true)
        .addChoices(monthsoption)
    )
    .addIntegerOption(option =>
        option.setName('day')
        .setNameLocalizations(getLoc('arg.day'))
        .setDescription('Type Day of timestamp you want to do')
        .setDescriptionLocalizations(getLoc('typetimestampday'))
        .setMinValue(1)
        .setMaxValue(31)
        .setRequired(true)
    )
    .addIntegerOption(option =>
        option.setName('hour')
        .setNameLocalizations(getLoc('arg.hour'))
        .setDescription('Type Hour of timestamp you want to do')
        .setDescriptionLocalizations(getLoc('typetimestamphour'))
        .setMinValue(0)
        .setMaxValue(23)
        .setRequired(false)
    )
    .addIntegerOption(option =>
        option.setName('minute')
        .setNameLocalizations(getLoc('arg.minute'))
        .setDescription('Type Minute of timestamp you want to do')
        .setDescriptionLocalizations(getLoc('typetimestampminute'))
        .setMinValue(0)
        .setMaxValue(59)
        .setRequired(false)
    )
    .addIntegerOption(option =>
        option.setName('second')
        .setNameLocalizations(getLoc('arg.second'))
        .setDescription('Type Second of timestamp you want to do')
        .setDescriptionLocalizations(getLoc('typetimestampsecond'))
        .setMinValue(0)
        .setMaxValue(59)
        .setRequired(false)
    )
    .addStringOption(option =>
        option.setName('timezone')
        .setNameLocalizations(getLoc('arg.timezone'))
        .setDescription('Select timezone of timestamp (Default: GMT+0)')
        .setDescriptionLocalizations(getLoc('seltimestamptimezone'))
        .setRequired(false)
        .addChoices(alltimezones)
    )
    .addStringOption(option =>
        option.setName('style')
        .setNameLocalizations(getLoc('arg.style'))
        .setDescription('Select style of date output')
        .setDescriptionLocalizations(getLoc('selectstyleformat'))
        .setRequired(false)
        .addChoices(timestampstyles)
    )
    .addBooleanOption(addPublicReply())
    
hosa.convertint = new SlashCommandBuilder()
    .setName('convert')
    .setDescription('🔄 Convert UNIX string to Date and backwards')
    setAvailable(hosa.convertint)
    .addSubcommand(subcommand =>
        subcommand.setName('tounix')
        .setDescription('🔄 Convert selected date to UNIX date integer')
        .setDescriptionLocalizations(getLoc('descconverttounix', '🔄 '))
        .addIntegerOption(option =>
            option.setName('year')
            .setNameLocalizations(getLoc('arg.year'))
            .setDescription('Type Year you want')
            .setDescriptionLocalizations(getLoc('typeyear'))
            .setMinValue(1601)
            .setMaxValue(3333)
            .setRequired(true)
        )
        .addStringOption(option =>
            option.setName('month')
            .setNameLocalizations(getLoc('arg.month'))
            .setDescription('Select Month you want')
            .setDescriptionLocalizations(getLoc('selmonth'))
            .setRequired(true)
            .addChoices(monthsoption)
        )
        .addIntegerOption(option =>
            option.setName('day')
            .setNameLocalizations(getLoc('arg.day'))
            .setDescription('Type Day you want')
            .setDescriptionLocalizations(getLoc('typeday'))
            .setMinValue(1)
            .setMaxValue(31)
            .setRequired(true)
        )
        .addBooleanOption(option =>
            option.setName('displayms')
            .setNameLocalizations(getLoc('arg.displayms'))
            .setDescription('Whether or not to return value with milliseconds')
            .setDescriptionLocalizations(getLoc('returnmilliseconds'))
            .setRequired(true)
        )
        .addIntegerOption(option =>
            option.setName('hour')
            .setNameLocalizations(getLoc('arg.hour'))
            .setDescription('Type Hour you want')
            .setDescriptionLocalizations(getLoc('typehour'))
            .setMinValue(0)
            .setMaxValue(23)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('minute')
            .setNameLocalizations(getLoc('arg.minute'))
            .setDescription('Type Minute you want')
            .setDescriptionLocalizations(getLoc('typeminute'))
            .setMinValue(0)
            .setMaxValue(59)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('second')
            .setNameLocalizations(getLoc('arg.second'))
            .setDescription('Type Second you want')
            .setDescriptionLocalizations(getLoc('typesecond'))
            .setMinValue(0)
            .setMaxValue(59)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('millisecond')
            .setNameLocalizations(getLoc('arg.millisecond'))
            .setDescription('Type Millisecond you want')
            .setDescriptionLocalizations(getLoc('typemillisecond'))
            .setMinValue(0)
            .setMaxValue(999)
            .setRequired(false)
        )
        .addStringOption(option =>
            option.setName('timezone')
            .setNameLocalizations(getLoc('arg.timezone'))
            .setDescription('Select timezone of input (Default: GMT+0)')
            .setDescriptionLocalizations(getLoc('seldatetimezone'))
            .setRequired(false)
            .addChoices(alltimezones)
        )
    )
    .addSubcommand(subcommand =>
        subcommand.setName('todate')
        .setDescription('🔄 Convert UNIX date integer to Human Date')
        .setDescriptionLocalizations(getLoc('descconverttodate', '🔄 '))
        .addIntegerOption(option =>
            option.setName('unixtime')
            .setNameLocalizations(getLoc('arg.unixtime'))
            .setDescription('Type UNIX Epoch Time Integer')
            .setDescriptionLocalizations(getLoc('typeunixtime'))
            .setMinValue(-8639999999999)
            .setMaxValue(8639999999999)
            .setRequired(true)
        )
        .addBooleanOption(option =>
            option.setName('withms')
            .setNameLocalizations(getLoc('arg.withms'))
            .setDescription('Whether or not to read and return value with milliseconds')
            .setDescriptionLocalizations(getLoc('readwithmilliseconds'))
            .setRequired(true)
        )
        .addStringOption(option =>
            option.setName('timezone')
            .setNameLocalizations(getLoc('arg.timezone'))
            .setDescription('Select timezone for output (Default: GMT+0)')
            .setDescriptionLocalizations(getLoc('outputtimezone'))
            .setRequired(false)
            .addChoices(alltimezones)
        )
    )

hosa.calcint = new SlashCommandBuilder()
    .setName('calc')
    .setDescription('🧮 Time and Date Calculator')
    setAvailable(hosa.calcint)
    .addSubcommand(subcommand =>
        subcommand.setName('fromnow')
        .setDescription('🧮 Add or subtract time from the current time')
        .setDescriptionLocalizations(getLoc('desccalcfromnow', '🧮 '))
        //Add or subtract
        .addStringOption(option =>
            option.setName('matharg')
            .setNameLocalizations(getLoc('arg.matharg'))
            .setDescription('ADD OR SUBTRACT')
            .setDescriptionLocalizations(getLoc('addorsub'))
            .setRequired(true)
            .addChoices(mathargs)
        )
        //offset to timezone
        .addStringOption(option =>
            option.setName('timezone')
            .setNameLocalizations(getLoc('arg.timezone'))
            .setDescription('Select timezone of input (Default: GMT+0)')
            .setDescriptionLocalizations(getLoc('seltimezone'))
            .setRequired(false)
            .addChoices(alltimezones)
        )
        //arg2
        .addIntegerOption(option =>
            option.setName('years')
            .setNameLocalizations(getLoc('arg.years'))
            .setDescription('ADD OR SUBTRACT this amount of years (Inaccurate. 365 days)')
            .setDescriptionLocalizations(getLoc('addorsubyears'))
            .setMinValue(0)
            .setMaxValue(1000)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('months')
            .setNameLocalizations(getLoc('arg.months'))
            .setDescription('ADD OR SUBTRACT this amount of months (Inaccurate. 30 days)')
            .setDescriptionLocalizations(getLoc('addorsubmonths'))
            .setMinValue(0)
            .setMaxValue(1000)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('weeks')
            .setNameLocalizations(getLoc('arg.weeks'))
            .setDescription('ADD OR SUBTRACT this amount of Weeks')
            .setDescriptionLocalizations(getLoc('addorsubweeks'))
            .setMinValue(0)
            .setMaxValue(5000)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('days')
            .setNameLocalizations(getLoc('arg.days'))
            .setDescription('ADD OR SUBTRACT this amount of Days')
            .setDescriptionLocalizations(getLoc('addorsubdays'))
            .setMinValue(0)
            .setMaxValue(50000)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('hours')
            .setNameLocalizations(getLoc('arg.hours'))
            .setDescription('ADD OR SUBTRACT this amount of Hours')
            .setDescriptionLocalizations(getLoc('addorsubhours'))
            .setMinValue(0)
            .setMaxValue(240000)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('minutes')
            .setNameLocalizations(getLoc('arg.minutes'))
            .setDescription('ADD OR SUBTRACT this amount of Minutes')
            .setDescriptionLocalizations(getLoc('addorsubminutes'))
            .setMinValue(0)
            .setMaxValue(1000000)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('seconds')
            .setNameLocalizations(getLoc('arg.seconds'))
            .setDescription('ADD OR SUBTRACT this amount of Seconds')
            .setDescriptionLocalizations(getLoc('addorsubseconds'))
            .setMinValue(0)
            .setMaxValue(100000000)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('milliseconds')
            .setNameLocalizations(getLoc('arg.milliseconds'))
            .setDescription('ADD OR SUBTRACT this amount of Milliseconds')
            .setDescriptionLocalizations(getLoc('addorsubmilliseconds'))
            .setMinValue(0)
            .setMaxValue(1000000000)
            .setRequired(false)
        )
        .addBooleanOption(addPublicReply())
    )
    //Calc with custom first arg
    .addSubcommand(subcommand =>
        subcommand.setName('fromdate')
        .setDescription('🧮 Add or subtract time from the specified date')
        .setDescriptionLocalizations(getLoc('desccalcfromdate', '🧮 '))
        //arg1
        .addIntegerOption(option =>
            option.setName('year')
            .setNameLocalizations(getLoc('arg.year'))
            .setDescription('Type Year to calculate from')
            .setDescriptionLocalizations(getLoc('typeyeartocountfrom'))
            .setMinValue(1601)
            .setMaxValue(3333)
            .setRequired(true)
        )
        .addStringOption(option =>
            option.setName('month')
            .setNameLocalizations(getLoc('arg.month'))
            .setDescription('Select Month to calculate from')
            .setDescriptionLocalizations(getLoc('selmonthtocountfrom'))
            .setRequired(true)
            .addChoices(monthsoption)
        )
        .addIntegerOption(option =>
            option.setName('day')
            .setNameLocalizations(getLoc('arg.day'))
            .setDescription('Type Day to calculate from')
            .setDescriptionLocalizations(getLoc('typedaytocountfrom'))
            .setMinValue(1)
            .setMaxValue(31)
            .setRequired(true)
        )
        //arg1
        .addIntegerOption(option =>
            option.setName('hour')
            .setNameLocalizations(getLoc('arg.hour'))
            .setDescription('Type Hour to calculate from')
            .setDescriptionLocalizations(getLoc('typehourtocountfrom'))
            .setMinValue(0)
            .setMaxValue(23)
            .setRequired(true)
        )
        .addIntegerOption(option =>
            option.setName('minute')
            .setNameLocalizations(getLoc('arg.minute'))
            .setDescription('Type Minute to calculate from')
            .setDescriptionLocalizations(getLoc('typeminutetocountfrom'))
            .setMinValue(0)
            .setMaxValue(59)
            .setRequired(true)
        )
        .addIntegerOption(option =>
            option.setName('second')
            .setNameLocalizations(getLoc('arg.second'))
            .setDescription('Type Second to calculate from')
            .setDescriptionLocalizations(getLoc('typesecondtocountfrom'))
            .setMinValue(0)
            .setMaxValue(59)
            .setRequired(true)
        )
        .addIntegerOption(option =>
            option.setName('millisecond')
            .setNameLocalizations(getLoc('arg.millisecond'))
            .setDescription('Type Millisecond to calculate from')
            .setDescriptionLocalizations(getLoc('typemillisecondtocountfrom'))
            .setMinValue(0)
            .setMaxValue(999)
            .setRequired(true)
        )
        //Add or subtract
        .addStringOption(option =>
            option.setName('matharg')
            .setNameLocalizations(getLoc('arg.matharg'))
            .setDescription('ADD OR SUBTRACT')
            .setDescriptionLocalizations(getLoc('addorsub'))
            .setRequired(true)
            .addChoices(mathargs)
        )
        //timezone of arg1
        .addStringOption(option =>
            option.setName('timezone')
            .setNameLocalizations(getLoc('arg.timezone'))
            .setDescription('Select timezone of input (Default: GMT+0)')
            .setDescriptionLocalizations(getLoc('seltimezone'))
            .setRequired(false)
            .addChoices(alltimezones)
        )
        //arg2
        .addIntegerOption(option =>
            option.setName('years')
            .setNameLocalizations(getLoc('arg.years'))
            .setDescription('ADD OR SUBTRACT this amount of years (Inaccurate. 365 days)')
            .setDescriptionLocalizations(getLoc('addorsubyears'))
            .setMinValue(0)
            .setMaxValue(1000)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('months')
            .setNameLocalizations(getLoc('arg.months'))
            .setDescription('ADD OR SUBTRACT this amount of months (Inaccurate. 30 days)')
            .setDescriptionLocalizations(getLoc('addorsubmonths'))
            .setMinValue(0)
            .setMaxValue(1000)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('weeks')
            .setNameLocalizations(getLoc('arg.weeks'))
            .setDescription('ADD OR SUBTRACT this amount of Weeks')
            .setDescriptionLocalizations(getLoc('addorsubweeks'))
            .setMinValue(0)
            .setMaxValue(5000)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('days')
            .setNameLocalizations(getLoc('arg.days'))
            .setDescription('ADD OR SUBTRACT this amount of Days')
            .setDescriptionLocalizations(getLoc('addorsubdays'))
            .setMinValue(0)
            .setMaxValue(50000)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('hours')
            .setNameLocalizations(getLoc('arg.hours'))
            .setDescription('ADD OR SUBTRACT this amount of Hours')
            .setDescriptionLocalizations(getLoc('addorsubhours'))
            .setMinValue(0)
            .setMaxValue(240000)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('minutes')
            .setNameLocalizations(getLoc('arg.minutes'))
            .setDescription('ADD OR SUBTRACT this amount of Minutes')
            .setDescriptionLocalizations(getLoc('addorsubminutes'))
            .setMinValue(0)
            .setMaxValue(1000000)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('seconds')
            .setNameLocalizations(getLoc('arg.seconds'))
            .setDescription('ADD OR SUBTRACT this amount of Seconds')
            .setDescriptionLocalizations(getLoc('addorsubseconds'))
            .setMinValue(0)
            .setMaxValue(100000000)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('milliseconds')
            .setNameLocalizations(getLoc('arg.milliseconds'))
            .setDescription('ADD OR SUBTRACT this amount of Milliseconds')
            .setDescriptionLocalizations(getLoc('addorsubmilliseconds'))
            .setMinValue(0)
            .setMaxValue(1000000000)
            .setRequired(false)
        )
        .addBooleanOption(addPublicReply())
    )
    //calculate time between dates
    .addSubcommand(subcommand =>
        subcommand.setName('from-to')
        .setDescription('🧮 Calculate time between two dates')
        .setDescriptionLocalizations(getLoc('desccalcfromto', '🧮 '))
        //first date
        .addIntegerOption(option =>
            option.setName('fromyear')
            .setNameLocalizations(getLoc('arg.fromyear'))
            .setDescription('Type first date Year')
            .setDescriptionLocalizations(getLoc('typefirstyear'))
            .setMinValue(1001)
            .setMaxValue(3333)
            .setRequired(true)
        )
        .addStringOption(option =>
            option.setName('frommonth')
            .setNameLocalizations(getLoc('arg.frommonth'))
            .setDescription('Select first date Month')
            .setDescriptionLocalizations(getLoc('selfirstmonth'))
            .setRequired(true)
            .addChoices(monthsoption)
        )
        .addIntegerOption(option =>
            option.setName('fromday')
            .setNameLocalizations(getLoc('arg.fromday'))
            .setDescription('Type first date Day')
            .setDescriptionLocalizations(getLoc('typefirstday'))
            .setMinValue(1)
            .setMaxValue(31)
            .setRequired(true)
        )
        //second date
        .addIntegerOption(option =>
            option.setName('toyear')
            .setNameLocalizations(getLoc('arg.toyear'))
            .setDescription('Type second date Year')
            .setDescriptionLocalizations(getLoc('typesecondyear'))
            .setMinValue(1001)
            .setMaxValue(3333)
            .setRequired(true)
        )
        .addStringOption(option =>
            option.setName('tomonth')
            .setNameLocalizations(getLoc('arg.tomonth'))
            .setDescription('Select second date Month')
            .setDescriptionLocalizations(getLoc('selsecondmonth'))
            .setRequired(true)
            .addChoices(monthsoption)
        )
        .addIntegerOption(option =>
            option.setName('today')
            .setNameLocalizations(getLoc('arg.today'))
            .setDescription('Type second date Day')
            .setDescriptionLocalizations(getLoc('typesecondday'))
            .setMinValue(1)
            .setMaxValue(31)
            .setRequired(true)
        )
        //first time
        .addIntegerOption(option =>
            option.setName('fromhour')
            .setNameLocalizations(getLoc('arg.fromhour'))
            .setDescription('Type first date Hour')
            .setDescriptionLocalizations(getLoc('typefirsthour'))
            .setMinValue(0)
            .setMaxValue(23)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('fromminute')
            .setNameLocalizations(getLoc('arg.fromminute'))
            .setDescription('Type first date Minute')
            .setDescriptionLocalizations(getLoc('typefirstminute'))
            .setMinValue(0)
            .setMaxValue(59)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('fromsecond')
            .setNameLocalizations(getLoc('arg.fromsecond'))
            .setDescription('Type first date Second')
            .setDescriptionLocalizations(getLoc('typefirstsecond'))
            .setMinValue(0)
            .setMaxValue(59)
            .setRequired(false)
        )
        //second time
        .addIntegerOption(option =>
            option.setName('tohour')
            .setNameLocalizations(getLoc('arg.tohour'))
            .setDescription('Type second date Hour')
            .setDescriptionLocalizations(getLoc('typesecondhour'))
            .setMinValue(0)
            .setMaxValue(23)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('tominute')
            .setNameLocalizations(getLoc('arg.tominute'))
            .setDescription('Type second date Minute')
            .setDescriptionLocalizations(getLoc('typesecondminute'))
            .setMinValue(0)
            .setMaxValue(59)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('tosecond')
            .setNameLocalizations(getLoc('arg.tosecond'))
            .setDescription('Type second date Second')
            .setDescriptionLocalizations(getLoc('typesecondsecond'))
            .setMinValue(0)
            .setMaxValue(59)
            .setRequired(false)
        )
        .addBooleanOption(addPublicReply())
    )

hosa.randomint = new SlashCommandBuilder()
    .setName('random')
    .setDescription('Get fully or custom range random Date and Time or Integer')
    setAvailable(hosa.randomint)
    .addSubcommand(subcommand =>
        subcommand.setName('date')
        .setDescription('🎲 Get random Date and Time with custom range support. First date: Min, Second date: Max')
        .setDescriptionLocalizations(getLoc('descranddate', '🎲 '))
        //first date
        .addIntegerOption(option =>
            option.setName('fromyear')
            .setNameLocalizations(getLoc('arg.fromyear'))
            .setDescription('Type first date Year')
            .setDescriptionLocalizations(getLoc('typefirstyear'))
            .setMinValue(1)
            .setMaxValue(3939)
            .setRequired(true)
        )
        //second date
        .addIntegerOption(option =>
            option.setName('toyear')
            .setNameLocalizations(getLoc('arg.toyear'))
            .setDescription('Type second date Year')
            .setDescriptionLocalizations(getLoc('typesecondyear'))
            .setMinValue(1)
            .setMaxValue(3939)
            .setRequired(true)
        )
        //first date
        .addStringOption(option =>
            option.setName('frommonth')
            .setNameLocalizations(getLoc('arg.frommonth'))
            .setDescription('Select first date Month')
            .setDescriptionLocalizations(getLoc('selfirstmonth'))
            .setRequired(false)
            .addChoices(monthsoption)
        )
        .addIntegerOption(option =>
            option.setName('fromday')
            .setNameLocalizations(getLoc('arg.fromday'))
            .setDescription('Type first date Day')
            .setDescriptionLocalizations(getLoc('typefirstday'))
            .setMinValue(1)
            .setMaxValue(31)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('fromhour')
            .setNameLocalizations(getLoc('arg.fromhour'))
            .setDescription('Type first date Hour')
            .setDescriptionLocalizations(getLoc('typefirsthour'))
            .setMinValue(0)
            .setMaxValue(23)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('fromminute')
            .setNameLocalizations(getLoc('arg.fromminute'))
            .setDescription('Type first date Minute')
            .setDescriptionLocalizations(getLoc('typefirstminute'))
            .setMinValue(0)
            .setMaxValue(59)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('fromsecond')
            .setNameLocalizations(getLoc('arg.fromsecond'))
            .setDescription('Type first date Second')
            .setDescriptionLocalizations(getLoc('typefirstsecond'))
            .setMinValue(0)
            .setMaxValue(59)
            .setRequired(false)
        )
        //second date
        .addStringOption(option =>
            option.setName('tomonth')
            .setNameLocalizations(getLoc('arg.tomonth'))
            .setDescription('Select second date Month')
            .setDescriptionLocalizations(getLoc('selsecondmonth'))
            .setRequired(false)
            .addChoices(monthsoption)
        )
        .addIntegerOption(option =>
            option.setName('today')
            .setNameLocalizations(getLoc('arg.today'))
            .setDescription('Type second date Day')
            .setDescriptionLocalizations(getLoc('typesecondday'))
            .setMinValue(1)
            .setMaxValue(31)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('tohour')
            .setNameLocalizations(getLoc('arg.tohour'))
            .setDescription('Type second date Hour')
            .setDescriptionLocalizations(getLoc('typesecondhour'))
            .setMinValue(0)
            .setMaxValue(23)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('tominute')
            .setNameLocalizations(getLoc('arg.tominute'))
            .setDescription('Type second date Minute')
            .setDescriptionLocalizations(getLoc('typesecondminute'))
            .setMinValue(0)
            .setMaxValue(59)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('tosecond')
            .setNameLocalizations(getLoc('arg.tosecond'))
            .setDescription('Type second date Second')
            .setDescriptionLocalizations(getLoc('typesecondsecond'))
            .setMinValue(0)
            .setMaxValue(59)
            .setRequired(false)
        )
        .addBooleanOption(addPublicReply())
    )
    .addSubcommand(subcommand =>
        subcommand.setName('integer')
        .setDescription('🎲 Get random integer with custom range support')
        .setDescriptionLocalizations(getLoc('descrandinteger', '🎲 '))
        .addIntegerOption(option =>
            option.setName('min')
            .setDescription('Type minimum possible integer')
            .setDescriptionLocalizations(getLoc('typemininteger'))
            .setMinValue(-999999999999999)
            .setMaxValue(999999999999999)
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option.setName('max')
            .setDescription('Type maximum possible integer')
            .setDescriptionLocalizations(getLoc('typemaxinteger'))
            .setMinValue(-999999999999999)
            .setMaxValue(999999999999999)
            .setRequired(false)
        )
        .addBooleanOption(addPublicReply())
    )
    .addSubcommand(subcommand =>
        subcommand.setName('dice')
        .setDescription('🎲 Throw a Dice! Also you can choose the dice! (Default: 1 ... 6)')
        .setDescriptionLocalizations(getLoc('descranddice', '🎲 '))
        .addStringOption(option =>
            option.setName('dicetype')
            .setDescription('Select type of dice')
            .setDescriptionLocalizations(getLoc('seldicetype'))
            .setRequired(false)
            .addChoices(dicetypes)
        )
        .addBooleanOption(addPublicReply())
    )
    

module.exports = { hosa };